// <auto-generated />
using System;
using KnitErp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnitErp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KnitErpDbContext))]
    [Migration("20261009144823_AddRecoveryCodes")]
    partial class AddRecoveryCodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kniterp")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnitErp.Domain.Access.OrganizationMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BlockedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long?>("BlockedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_members_org_user");

                    b.ToTable("organization_members", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_organization_members_blocked", "[Status] <> 2 OR [BlockedAtUtc] IS NOT NULL");

                            t.HasCheckConstraint("ck_organization_members_status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Access.RecoveryCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ux_user_recovery_codes_user_hash");

                    b.ToTable("user_recovery_codes", "kniterp");
                });

            modelBuilder.Entity("KnitErp.Domain.Access.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_org_code");

                    b.ToTable("roles", "kniterp");
                });

            modelBuilder.Entity("KnitErp.Domain.Access.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("GrantedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeny")
                        .HasColumnType("bit");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long?>("RevokedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ValidFromUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("ValidToUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long?>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "DepartmentId");

                    b.HasIndex("OrganizationId", "UserId")
                        .HasDatabaseName("ix_role_assignments_org_user");

                    b.HasIndex("OrganizationId", "WarehouseId");

                    b.ToTable("role_assignments", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_role_assignments_deny", "[IsDeny] = 0 OR [PermissionCode] IS NOT NULL");

                            t.HasCheckConstraint("ck_role_assignments_deny_reason", "[IsDeny] = 0 OR [Reason] IS NOT NULL");

                            t.HasCheckConstraint("ck_role_assignments_period", "[ValidToUtc] IS NULL OR [ValidToUtc] > [ValidFromUtc]");

                            t.HasCheckConstraint("ck_role_assignments_target", "([RoleId] IS NOT NULL AND [PermissionCode] IS NULL) OR ([RoleId] IS NULL AND [PermissionCode] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Access.RolePermission", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint");

                    b.HasKey("RoleId", "PermissionCode");

                    b.ToTable("role_permissions", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_role_permissions_level", "[Level] IN (1, 2, 3, 10, 11)");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Access.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthenticatorKey")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<int>("FailedSignInCount")
                        .HasColumnType("int");

                    b.Property<long?>("LastTotpStep")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SetupTokenExpiresAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("SetupTokenHash")
                        .HasColumnType("binary(32)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("SetupTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_users_setup_token")
                        .HasFilter("[SetupTokenHash] IS NOT NULL");

                    b.ToTable("users", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_users_2fa_key", "[TwoFactorEnabled] = 0 OR [AuthenticatorKey] IS NOT NULL");

                            t.HasCheckConstraint("ck_users_failed_sign_in", "[FailedSignInCount] >= 0");

                            t.HasCheckConstraint("ck_users_setup_token", "([SetupTokenHash] IS NULL AND [SetupTokenExpiresAtUtc] IS NULL) OR ([SetupTokenHash] IS NOT NULL AND [SetupTokenExpiresAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("ck_users_status", "[Status] IN (1, 2, 4)");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Audit.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("After")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Before")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte[]>("ChainHash")
                        .HasColumnType("binary(32)");

                    b.Property<long?>("ChainSeq")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ChainSeq")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_log_org_chain")
                        .HasFilter("[ChainSeq] IS NOT NULL");

                    b.HasIndex("OrganizationId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_log_org_time");

                    b.ToTable("audit_log", "kniterp", t =>
                        {
                            t.HasTrigger("tr_audit_log_immutable");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KnitErp.Domain.Catalog.Counterparty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Inn")
                        .HasColumnType("varchar(12)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSupplier")
                        .HasColumnType("bit");

                    b.Property<string>("Kpp")
                        .HasColumnType("char(9)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_counterparties_org_id");

                    b.HasIndex("OrganizationId", "Name")
                        .HasDatabaseName("ix_counterparties_org_name");

                    b.HasIndex("OrganizationId", "Inn", "Kpp")
                        .IsUnique()
                        .HasDatabaseName("ux_counterparties_org_inn_kpp_active")
                        .HasFilter("[Inn] IS NOT NULL AND [IsArchived] = 0");

                    b.ToTable("counterparties", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_counterparties_inn", "[Inn] IS NULL OR ((LEN([Inn]) = 10 OR LEN([Inn]) = 12) AND [Inn] NOT LIKE '%[^0-9]%')");

                            t.HasCheckConstraint("ck_counterparties_kpp", "[Kpp] IS NULL OR (LEN([Kpp]) = 9 AND LEN([Inn]) = 10)");

                            t.HasCheckConstraint("ck_counterparties_role", "[IsSupplier] = 1 OR [IsCustomer] = 1");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Catalog.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_items_org_id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_items_org_code");

                    b.HasIndex("OrganizationId", "UnitId");

                    b.HasIndex("OrganizationId", "Type", "Name")
                        .HasDatabaseName("ix_items_org_type_name");

                    b.ToTable("items", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_items_archived", "[IsArchived] = 0 OR [ArchivedAtUtc] IS NOT NULL");

                            t.HasCheckConstraint("ck_items_type", "[Type] IN (1, 2, 3, 4, 5, 6, 9)");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Catalog.UnitOfMeasure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Precision")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_units_org_id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_units_org_code");

                    b.ToTable("units", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_units_precision", "[Precision] BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Common.DocumentCounter", b =>
                {
                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("LastNumber")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OrganizationId", "Kind");

                    b.ToTable("document_counters", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_document_counters_last", "[LastNumber] >= 0");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Organizations.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Kpp")
                        .HasColumnType("char(9)");

                    b.Property<bool>("KppVerified")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Inn")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_inn");

                    b.ToTable("organizations", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_organizations_currency", "LEN([CurrencyCode]) = 3");

                            t.HasCheckConstraint("ck_organizations_inn", "LEN([Inn]) = 10 AND [Inn] NOT LIKE '%[^0-9]%'");

                            t.HasCheckConstraint("ck_organizations_kpp", "[Kpp] IS NULL OR LEN([Kpp]) = 9");

                            t.HasCheckConstraint("ck_organizations_kpp_verified", "[KppVerified] = 0 OR [Kpp] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Structure.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_departments_org_id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_departments_org_name_active")
                        .HasFilter("[IsArchived] = 0");

                    b.HasIndex("OrganizationId", "ParentId");

                    b.ToTable("departments", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_departments_archived", "[IsArchived] = 0 OR [ArchivedAtUtc] IS NOT NULL");

                            t.HasCheckConstraint("ck_departments_not_self_parent", "[ParentId] IS NULL OR [ParentId] <> [Id]");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Structure.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("DismissedOn")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("HiredOn")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "DepartmentId")
                        .HasDatabaseName("ix_employees_org_department");

                    b.HasIndex("OrganizationId", "PersonnelNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_org_number");

                    b.HasIndex("OrganizationId", "PositionId");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_org_user")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("employees", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_employees_dismissed", "([Status] = 9 AND [DismissedOn] IS NOT NULL AND [DismissedOn] >= [HiredOn]) OR ([Status] <> 9 AND [DismissedOn] IS NULL)");

                            t.HasCheckConstraint("ck_employees_status", "[Status] IN (1, 2, 9)");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Structure.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_positions_org_id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_positions_org_name_active")
                        .HasFilter("[IsArchived] = 0");

                    b.ToTable("positions", "kniterp");
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.InventoryCount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("CountDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long?>("PostedByUserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_inventory_counts_org_id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PostedByUserId");

                    b.HasIndex("OrganizationId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_counts_org_number");

                    b.HasIndex("OrganizationId", "WarehouseId");

                    b.ToTable("inventory_counts", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_counts_posted", "([Status] = 2 AND [PostedByUserId] IS NOT NULL AND [PostedAtUtc] IS NOT NULL) OR ([Status] <> 2 AND [PostedByUserId] IS NULL)");

                            t.HasCheckConstraint("ck_inventory_counts_status", "[Status] IN (1, 2, 9)");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.InventoryLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BookQuantity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("CountedQuantity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("DocumentId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_lines_doc_item");

                    b.ToTable("inventory_lines", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_lines_counted", "[CountedQuantity] IS NULL OR [CountedQuantity] >= 0");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.OpeningBalance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long?>("ApprovedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReturnReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_opening_balances_org_id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrganizationId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_opening_balances_org_number");

                    b.HasIndex("OrganizationId", "WarehouseId");

                    b.ToTable("opening_balances", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_opening_balances_approved", "([Status] = 3 AND [ApprovedByUserId] IS NOT NULL AND [ApprovedAtUtc] IS NOT NULL AND [ApprovedByUserId] <> [CreatedByUserId]) OR ([Status] <> 3 AND [ApprovedByUserId] IS NULL)");

                            t.HasCheckConstraint("ck_opening_balances_status", "[Status] IN (1, 2, 3, 9)");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.OpeningBalanceLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("DocumentId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_opening_balance_lines_doc_item");

                    b.ToTable("opening_balance_lines", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_opening_balance_lines_quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.OperationReason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("RequiresComment")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_operation_reasons_org_id");

                    b.HasIndex("OrganizationId", "Kind", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_operation_reasons_org_kind_name_active")
                        .HasFilter("[IsArchived] = 0");

                    b.ToTable("operation_reasons", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_operation_reasons_kind", "[Kind] IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.PeriodClosure", b =>
                {
                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("ChangedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("ClosedThrough")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OrganizationId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("period_closures", "kniterp");
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.Site", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_sites_org_id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_sites_org_name_active")
                        .HasFilter("[IsArchived] = 0");

                    b.ToTable("sites", "kniterp");
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.StockDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("CounterpartyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("date");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long?>("PostedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReasonId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReversalReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReversedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long?>("ReversedByUserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<long?>("TargetWarehouseId")
                        .HasColumnType("bigint");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_stock_documents_org_id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PostedByUserId");

                    b.HasIndex("ReversedByUserId");

                    b.HasIndex("OrganizationId", "CounterpartyId");

                    b.HasIndex("OrganizationId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_stock_documents_org_number");

                    b.HasIndex("OrganizationId", "ReasonId");

                    b.HasIndex("OrganizationId", "TargetWarehouseId");

                    b.HasIndex("OrganizationId", "WarehouseId");

                    b.HasIndex("OrganizationId", "Kind", "DocumentDate")
                        .HasDatabaseName("ix_stock_documents_org_kind_date");

                    b.ToTable("stock_documents", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_stock_documents_counterparty", "[Kind] = 1 OR [CounterpartyId] IS NULL");

                            t.HasCheckConstraint("ck_stock_documents_kind", "[Kind] IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_stock_documents_posted", "([Status] IN (2, 3) AND [PostedByUserId] IS NOT NULL AND [PostedAtUtc] IS NOT NULL AND [ReasonId] IS NOT NULL) OR ([Status] NOT IN (2, 3) AND [PostedByUserId] IS NULL)");

                            t.HasCheckConstraint("ck_stock_documents_reversed", "([Status] = 3 AND [ReversedByUserId] IS NOT NULL AND [ReversedAtUtc] IS NOT NULL AND [ReversalReason] IS NOT NULL) OR ([Status] <> 3 AND [ReversedByUserId] IS NULL)");

                            t.HasCheckConstraint("ck_stock_documents_status", "[Status] IN (1, 2, 3, 9)");

                            t.HasCheckConstraint("ck_stock_documents_target", "([Kind] = 3 AND [TargetWarehouseId] IS NOT NULL AND [TargetWarehouseId] <> [WarehouseId]) OR ([Kind] <> 3 AND [TargetWarehouseId] IS NULL)");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.StockDocumentLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("DocumentId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_stock_document_lines_doc_item");

                    b.ToTable("stock_document_lines", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_stock_document_lines_quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.StockMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("ChainHash")
                        .HasColumnType("binary(32)");

                    b.Property<long?>("ChainSeq")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ChainSeq")
                        .IsUnique()
                        .HasDatabaseName("ux_stock_movements_org_chain")
                        .HasFilter("[ChainSeq] IS NOT NULL");

                    b.HasIndex("OrganizationId", "ItemId");

                    b.HasIndex("Source", "SourceId")
                        .HasDatabaseName("ix_stock_movements_source");

                    b.HasIndex("OrganizationId", "WarehouseId", "ItemId")
                        .HasDatabaseName("ix_stock_movements_org_wh_item");

                    b.ToTable("stock_movements", "kniterp", t =>
                        {
                            t.HasTrigger("tr_stock_movements_closed_period");

                            t.HasTrigger("tr_stock_movements_immutable");

                            t.HasCheckConstraint("ck_stock_movements_quantity", "[Quantity] <> 0");

                            t.HasCheckConstraint("ck_stock_movements_source", "[Source] IN (1, 2, 3, 4)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.Warehouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SiteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_warehouses_org_id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_warehouses_org_name_active")
                        .HasFilter("[IsArchived] = 0");

                    b.HasIndex("OrganizationId", "SiteId");

                    b.ToTable("warehouses", "kniterp");
                });

            modelBuilder.Entity("KnitErp.Domain.Workspace.SupportTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Answer")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long?>("AnsweredByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Section")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("UnreadByAuthor")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("AnsweredByUserId");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("OrganizationId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_support_tickets_org_number");

                    b.HasIndex("OrganizationId", "AuthorUserId", "Status")
                        .HasDatabaseName("ix_support_tickets_org_author_status");

                    b.ToTable("support_tickets", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_support_tickets_answer", "[Status] <> 3 OR ([Answer] IS NOT NULL AND [AnsweredByUserId] IS NOT NULL)");

                            t.HasCheckConstraint("ck_support_tickets_status", "[Status] IN (1, 2, 3, 9)");
                        });
                });

            modelBuilder.Entity("KnitErp.Domain.Workspace.UserToolData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_user_tool_data_org_user_kind");

                    b.ToTable("user_tool_data", "kniterp", t =>
                        {
                            t.HasCheckConstraint("ck_user_tool_data_size", "LEN([Json]) <= 200000");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", "kniterp");
                });

            modelBuilder.Entity("KnitErp.Domain.Access.OrganizationMember", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Access.RecoveryCode", b =>
                {
                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Access.Role", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Access.RoleAssignment", b =>
                {
                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KnitErp.Domain.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Structure.Department", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "DepartmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_role_assignments_department");

                    b.HasOne("KnitErp.Domain.Warehousing.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "WarehouseId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_role_assignments_warehouse");
                });

            modelBuilder.Entity("KnitErp.Domain.Access.RolePermission", b =>
                {
                    b.HasOne("KnitErp.Domain.Access.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Catalog.Counterparty", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Catalog.Item", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Catalog.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UnitId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_items_unit");
                });

            modelBuilder.Entity("KnitErp.Domain.Catalog.UnitOfMeasure", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Common.DocumentCounter", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Structure.Department", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Structure.Department", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ParentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_departments_parent");
                });

            modelBuilder.Entity("KnitErp.Domain.Structure.Employee", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KnitErp.Domain.Structure.Department", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "DepartmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_department");

                    b.HasOne("KnitErp.Domain.Structure.Position", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PositionId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_position");
                });

            modelBuilder.Entity("KnitErp.Domain.Structure.Position", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.InventoryCount", b =>
                {
                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("PostedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KnitErp.Domain.Warehousing.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "WarehouseId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_counts_warehouse");
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.InventoryLine", b =>
                {
                    b.HasOne("KnitErp.Domain.Warehousing.InventoryCount", null)
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Catalog.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.OpeningBalance", b =>
                {
                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Warehousing.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "WarehouseId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_opening_balances_warehouse");
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.OpeningBalanceLine", b =>
                {
                    b.HasOne("KnitErp.Domain.Warehousing.OpeningBalance", null)
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Catalog.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.OperationReason", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.PeriodClosure", b =>
                {
                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithOne()
                        .HasForeignKey("KnitErp.Domain.Warehousing.PeriodClosure", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.Site", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.StockDocument", b =>
                {
                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("PostedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ReversedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KnitErp.Domain.Catalog.Counterparty", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CounterpartyId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_documents_counterparty");

                    b.HasOne("KnitErp.Domain.Warehousing.OperationReason", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ReasonId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_documents_reason");

                    b.HasOne("KnitErp.Domain.Warehousing.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TargetWarehouseId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_documents_target_warehouse");

                    b.HasOne("KnitErp.Domain.Warehousing.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "WarehouseId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_documents_warehouse");
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.StockDocumentLine", b =>
                {
                    b.HasOne("KnitErp.Domain.Warehousing.StockDocument", null)
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Catalog.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.StockMovement", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Catalog.Item", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ItemId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_item");

                    b.HasOne("KnitErp.Domain.Warehousing.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "WarehouseId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_warehouse");
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.Warehouse", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Warehousing.Site", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "SiteId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_warehouses_site");
                });

            modelBuilder.Entity("KnitErp.Domain.Workspace.SupportTicket", b =>
                {
                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AnsweredByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Workspace.UserToolData", b =>
                {
                    b.HasOne("KnitErp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnitErp.Domain.Access.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnitErp.Domain.Access.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.InventoryCount", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.OpeningBalance", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("KnitErp.Domain.Warehousing.StockDocument", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
