<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>KnitErp.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KnitErp.Application\KnitErp.Application.csproj" />
    <ProjectReference Include="..\KnitErp.Infrastructure\KnitErp.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="QRCoder" />
  </ItemGroup>
</Project>
